### ISSUE TITLE
Select and add template engine

### ISSUE THREAD

**Issue by mvarga6** [brodia10/Multi-Pong#21]
We'd like to be able to fill the static pages with dynamic data from the server. This will require us to pick a JS template engine and convert the serving of the `static` folder at `/` to more explicit route handler functions.

**Comment by mvarga6** [comment]
I think I'm gonna go with https://eta.js.org/ after looking into a bunch.

**Comment by brodia10** [comment]
Cool sounds good to me just checked it out a little bit. A template engine is like Jinja2 for django right?

**Comment by mvarga6** [comment]
Yup yup!
