### ISSUE TITLE
Site Landing Page Wireframes

### ISSUE THREAD

**Issue by mvarga6** [brodia10/Multi-Pong#7]
The site needs a landing page that has some basic features:

1. Display current game rooms
2. Join a game room
3. Create a new game room

While the server is being developed, we can progress the design this page using mock data.

The data we need to display related to a game room:
- Title
- Players name in the room
- Score
- Elapsed time (if it's started)

Results:
- A placeholder page `index.html` that "Looks" like we want it to look like but with fake data.
- Serve this page as the landing page (hence making it index.html)

**Comment by brodia10** [comment]
So be to clear I'm designing an placeholder landing page (html) and not just designing a wireframe (a picture of what the html will look like once implemented)?
